version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: flightdata_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: flightdata_redis
    ports:
      - "6379:6379"
